apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.deploymentAndServiceName }}
spec:
  type: {{ .Values.redis.serviceType }}
  selector:
    app: {{ .Values.redis.deploymentAndServiceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
