services:
  mssql:
    image: my-mssql
    container_name: my-mssql
    build:
      context: .
      dockerfile: Dockerfile.mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: 'S0f1a^2025_Data!1'
      APP_DB_NAME: "mydb"
      APP_DB_LOGIN: "cash100m"
      APP_DB_PASSWORD: 'S0f1a^2025_Data!1'
    ports:
      - "1433:1433"
    # Persist data by mounting /var/opt/mssql (or just use named volumes)
    # volumes:
    #   - mssql-data:/var/opt/mssql
# volumes:
#   mssql-data:
